# fail_fast: true
minimum_pre_commit_version: 4.5.0
exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      docs/_build/.*|
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
      .direnv/.*|
      .yarn/.*|
      .ansible/.*|
      node_modules/.*|
      public/reports/.*|
      .npm/.*|
      .nuxt/.*|
      .netlify.*|
      .vercel/.*|
  )$
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
    - pyright
    - schemas
  submodules: true
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # ---------------------------------------------------------------------------- #
  #                              ðŸ”„ Pre-Commit Hooks                             #
  # ---------------------------------------------------------------------------- #
  # - repo: meta
  #   hooks:
  #     - id: check-useless-excludes
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      - id: pre-commit-update

    # ---------------------------- ðŸ“ Filesystem Tools --------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Remove trailing whitespace"
        args: [--markdown-linebreak-ext=md]
        exclude: >
          (?x)^(
              api/honeypot/.*|
          )$
      - id: fix-byte-order-marker
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Verify byte order"
      - id: mixed-line-ending
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Verify mixed line ending"
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Verify end of file"
        exclude: >
          (?x)^(
              api/honeypot/.*|
          )$
      - id: check-executables-have-shebangs
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Verify shebang preset"
        # exclude: >
        #   (?x)^(
        #       .mvn/|
        #       .venv|
        #       .direnv|
        #   )$
      - id: check-shebang-scripts-are-executable
        name: "ðŸ“ filesystem/âš™ï¸ exec Â· Verify script permissions"
      - id: check-symlinks
        name: "ðŸ“ filesystem/ðŸ”— symlink Â· Check symlink validity"
      - id: destroyed-symlinks
        name: "ðŸ“ filesystem/ðŸ”— symlink Â· Detect broken symlinks"
      - id: debug-statements
        name: "ðŸ“ filesystem/ðŸ“ debug Â· Check debug statements"
      - id: check-ast
        name: "ðŸ“ filesystem/ðŸ“ ast Â· Check ast"
      - id: check-builtin-literals
        name: "ðŸ“ filesystem/ðŸ“ literals Â· Check builtin literals"
      - id: check-case-conflict
        name: "ðŸ“ filesystem/ðŸ“ names Â· Check case sensitivity"
      - id: check-illegal-windows-names
        name: "ðŸ“ filesystem/ðŸ“ names Â· Validate Windows filenames"
      - id: check-docstring-first
        name: "ðŸ“ filesystem/ðŸ“ docstring Â· Validate docstring first"
      - id: name-tests-test
        name: "ðŸ“ filesystem/ðŸ“ names Â· Check tests names"

        # --------------------------- ðŸ” Code Quality Tools -------------------------- #
      - id: check-json
        name: "ðŸ“ filesystem/ðŸ“ json Â· Check json"
        exclude: >
          (?x)^(
            ^.vscode/.*|
            .devcontainer/devcontainer.json|
          )$
      - id: check-toml
        name: "ðŸ“ filesystem/ðŸ“œ toml - Check toml"
      - id: check-xml
        name: "ðŸ“ filesystem/ðŸ“œ xml - Check xml"
      - id: check-yaml
        name: "ðŸ“ filesystem/ðŸ“œ yaml - Check yaml"
        args: [--allow-multiple-documents]
        exclude: >
          (?x)^(
            .gitlab-ci.yml|
          )$
      - id: sort-simple-yaml
        name: "ðŸ”€ sort/ðŸ“œ yaml - Sort yaml"
      - id: file-contents-sorter
        name: "ðŸ”€ sort/ðŸ“œ file Â· Sort contents"
      - id: requirements-txt-fixer
        name: "ðŸ”€ sort/ðŸ json Â· Sort requirements"
        # ------------------------------- ðŸŒ³ Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: "ðŸŒ³ git Â· Detect conflict markers"
      - id: forbid-new-submodules
        name: "ðŸŒ³ git Â· Prevent submodule creation"
        # - id: no-commit-to-branch
        #   name: "ðŸŒ³ git Â· Protect main branches"
        #   args: [--branch, main, --branch, master, --branch, release/*]
      - id: check-added-large-files
        name: "ðŸŒ³ git Â· Block large file commits"
        args: [--maxkb=123]
        exclude: >
          (?x)^(
            .pnp.cjs|
            package-lock.json|
            my-app/package-lock.json|
            npm-shrinkwrap.json|
            poetry.lock|
            Pipfile.lock|
            yarn.lock|
            sbom.json|
            pnpm-lock.yaml|
            public/wireframe.css|
            cv/cv-aandrieu-XX-XX-.*|
            vue-client/package-lock.json|
            public/assets/fontawesome-free-7.1.0-web/.*|
            public/assets/fontawesome/.*|
          )$
        # ----------------------------- ðŸ”’ Security Tools ---------------------------- #
      - id: detect-private-key
        name: "ðŸ”’ security Â· Detect private keys"

  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v4.5.1
    hooks:
      - id: validate_manifest
        name: "ðŸ¤– manifest Â· Validate manifest scripts"

  - repo: https://github.com/doublify/pre-commit-hindent.git
    rev: b3680b6ebf9f7cf29b19307f246adef66756feef
    hooks:
      - id: hindent
        name: "ðŸ¤– hindent Â· Format scripts"

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma
        name: "ðŸ¤– comma Â· Add trailing comma"

    # --------------------------- ðŸ” Code Quality Tools -------------------------- #

    ### Python Tools ###
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: "ðŸ python Â· Py Upgrade"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff-format
        name: "ðŸ python Â· Format with Ruff"

      - id: ruff
        name: "ðŸ python Â· Lint and perform unsafe auto-fixes with Ruff"
        args: [--unsafe-fixes]

      - id: ruff-check
        name: "ðŸ python Â· Check with Ruff"
        args: [--fix]

    # - repo: https://github.com/RobertCraigie/pyright-python
    #   rev: v1.1.406
    #   hooks:
    #     - id: pyright
    #       name: "ðŸ python Â· Check types"

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: "ðŸ python Â· Validate pyproject.toml"
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

    # ----------------------------- âš¡ï¸ uv Build Tools ---------------------------- #
    # This helps ensure cross-compatibility with people who don't wish to use uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.24
    hooks:
      - id: uv-sync
        name: "âš¡ï¸ uv Â· Sync dependencies with uv"
      - id: uv-lock
        name: "âš¡ï¸ uv Â· Update dependency lockfile"
      - id: uv-lock
        name: "âš¡ï¸ uv Â· Upgrade via uv sync --upgrade"
        alias: deps
        args: ["--upgrade"]
        stages: [manual]
      - id: uv-export
        name: "âš¡ï¸ uv Â· Export dependencies to requirements.txt"
        args:
          - "--no-dev"
          - "--no-emit-package"
          - ansible-core
          - "--no-emit-package"
          - resolvelib
          - "--no-emit-package"
          - ruamel-yaml-clib
          - "--no-emit-package"
          - tomli
          - "--no-emit-package"
          - typing-extensions
          - "--no-emit-project"
          - "--no-hashes"
          - "-o"
          - ".config/requirements-lock.txt"

    ### Shell ###
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      # Choose one of:
      # - id: shfmt         # native (requires Go to build)
      - id: shfmt-docker # Docker image (requires Docker to run)
        name: "ðŸš ðŸ³ shell Â· Format shell scripts"
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        name: "ðŸš shell Â· Lint shell scripts"
        args: [-x]
        exclude: >
          (?x)^(
            hooks|
            tests/.*|
            .envrc|
            scripts/run-wicked.sh|
          )$

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: "ðŸš shell Â· Check shell script code style"
        args: [-i, "E003,E006"]
        exclude: >
          (?x)^(
            trunk|
            scripts/run-python.sh|
            scripts/run-wicked.sh|
            .envrc|
          )$

    ### Makefile ###
  - repo: https://github.com/mrtazz/checkmake.git
    rev: v0.3.2
    hooks:
      - id: checkmake
        name: "ðŸ® Makefile Â· Lint Makefile"

    ### SQL ###
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.5.0
    hooks:
      - id: sqlfluff-fix
        name: "ðŸ“Š SQL Â· Attempts to fix rule violations."
      - id: sqlfluff-lint
        name: "ðŸ“Š SQL Â· Lint SQL code files"

    ### Notebooks ###
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        entry: nbqa mdformat
        name: "ðŸ““ notebook Â· Format markdown cells"
        args: ["--nbqa-md"]
        types: [jupyter]
        additional_dependencies:
          - mdformat
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff
        # - id: nbqa-mypy
        #   name: "ðŸ““ notebook Â· Type-check cells"

    ### Markdown ###
    # - repo: https://github.com/hukkin/mdformat
    #   rev: 1.0.0
    #   hooks:
    #     - id: mdformat
    #       name: "ðŸ“ markdown Â· Format markdown"
    #       additional_dependencies:
    #         - mdformat-gfm # GitHub-Flavored Markdown support
    #         - mdformat-ruff # Python code formatting
    #         - mdformat-frontmatter # YAML frontmatter support
    #         - ruff # Required for mdformat-ruff

    ### Markdown ###
    # - repo: https://github.com/hukkin/mdformat
    #   rev: 1.0.0
    #   hooks:
    #     - id: mdformat
    #       name: "ðŸ“ markdown Â· Format markdown"
    #       additional_dependencies:
    #         - mdformat-gfm # GitHub-Flavored Markdown support
    #         - mdformat-ruff # Python code formatting
    #         - mdformat-frontmatter # YAML frontmatter support
    #         - ruff # Required for mdformat-ruff
    # - repo: https://github.com/markdownlint/markdownlint
    #   rev: v0.15.0
    #   hooks:
    #     - id: markdownlint
    #       name: "ðŸ“ markdown Â· Lint markdown"
    #       exclude: >
    #         (?x)^(
    #             CHANGELOG.md|
    #             README.md|
    #         )$

    ### Javascript & Web Tools ###
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.11"
    hooks:
      - id: biome-check
        name: "ðŸŸ¨ javascript Â· Lint, format, and safe fixes with Biome"
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        exclude: >
          (?x)^(
              trivy-sbom.json|
              my-app/public/.*|
              public/assets/fontawesome-free-7.1.0-web/.*|
              public/assets/fontawesome/.*|
              public/assets/.*|
              public/arf.js|
              public/index.js|
              public/d3.v3.min.js|
              api/hello.js|
          )$

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmllint
        name: "ðŸ“ html Â· Lint html"
        args: [--config, .eslintrc.json]
        files: ^src/
      - id: htmlhint
        name: "ðŸ“ html Â· Hint html"
        args: [--config, .htmlhintrc]
        exclude: >
          (?x)^(
            public/reports/monitoring_report.html|
            public/reports/chkrootkit-report.html|
            public/reports/maldet-report.html|
          )$
      - id: markdown-toc
        name: "ðŸ“ markdown Â· Toc markdown"
        args: [--maxdepth, "3", -i]

    ### PNG Images ###
    # - repo: https://github.com/shssoichiro/oxipng
    #   rev: v9.1.5
    #   hooks:
    #     - id: oxipng
    #       name: "ðŸ–¼ï¸ images Â· Optimize PNG files"
    #       args: ["-o", "4", "--strip", "safe", "--alpha"]

    ### Additional File Types ###
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: "âœ¨ misc-files Â· Format misc web files"
        types_or: [yaml, html, scss]
        additional_dependencies:
          - prettier@3.4.2
        exclude: >
          (?x)^(
            pnpm-lock.yaml|
            public/login.html|
            public/cv/index.html|
            public/reports/monitoring_report.html|
            api/honeypot/.*|
            public/assets/fontawesome-free-7.1.0-web/.*|
            public/assets/fontawesome/.*|
          )$

    ### Data & Config Validation ###
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.0
    hooks:
      - id: check-github-workflows
        name: "ðŸ§© github-actions Â· Validate gh workflow files"
        args: ["--verbose"]
      - id: check-taskfile
        name: "âœ… taskfile Â· Validate Task configuration"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        name: "ðŸ³ hadolint Â· Validate Dockerfile"

    # ----------------------------- ðŸ”’ Security Tools ---------------------------- #

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        name: "ðŸ”’ security Â· Detect security issues"
        args: [-c, .bandit.yml]

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.1
    hooks:
      - id: encryption-check
        name: "ðŸ”’ security Â· Detect encryption"
        exclude: >
          (?x)^(
            public/assets/fontawesome-free-7.1.0-web/.*|
          )$

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks-docker
        name: "ðŸ”’ ðŸ³ security Â· Detect hardcoded secrets"
        entry: zricethezav/gitleaks protect --verbose --redact --staged

    ### Ansible ###
    # Disable because too slow
    # - repo: https://github.com/ansible-community/ansible-lint.git
    #   rev: v25.9.2
    #   hooks:
    #     - id: ansible-lint
    #       name: "ðŸ“œ ansible - Lint Ansible"
    #       # args: [--verbose]
    #       files: \.(yaml|yml)$
    #       exclude: >
    #         (?x)^(
    #            .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
    #            docs/site/.*|       # Exclude mkdocs compiled files
    #            docs/_build/.*|
    #            \.history/.*|       # Exclude history files
    #            .*cache.*/.*|       # Exclude cache directories
    #            .*venv.*/.*|        # Exclude virtual environment directories
    #            .direnv/.*|
    #            .yarn/.*|
    #            .ansible/.*|
    #            node_modules/.*|
    #            reports/.*|
    #            .npm/.*|
    #            .nuxt/.*|
    #            .netlify.*|
    #            .vercel/.*|
    #            .travis.yml|
    #            docker/|
    #            requirements.yml|
    #           playbooks/group_vars/all/vault.yml|
    #            .gitlab-ci.yml|
    #          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: "ðŸ“œ yamllint - Lint Yaml"
        args: [--format, parsable, --strict]
        exclude: >
          (?x)^(
            .pnp.cjs|
            package-lock.json|
            bababou-app/package-lock.json|
            npm-shrinkwrap.json|
            poetry.lock|
            Pipfile.lock|
            yarn.lock|
            sbom.json|
            pnpm-lock.yaml|
          )$
